In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
df = pd.read_csv("iris.csv")

print("First 5 Rows:")
print(df.head())

print("\nShape of Dataset:")
print(df.shape)

print("\nColumns:")
print(df.columns)


First 5 Rows:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Shape of Dataset:
(150, 5)

Columns:
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')


In [3]:
print("\nMissing Values:")
print(df.isnull().sum())


Missing Values:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [4]:

X = df.drop("species", axis=1)
y = df["species"]

In [5]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42
)


In [6]:
model = GaussianNB()
model.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [7]:
y_pred = model.predict(X_test)

print("\nPredicted Values:")
print(y_pred[:10])


Predicted Values:
['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']


In [8]:

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)


Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [9]:
TP = cm[0][0]
FP = cm[:,0].sum() - TP
FN = cm[0,:].sum() - TP
TN = cm.sum() - (TP + FP + FN)

print("\nTP =", TP)
print("FP =", FP)
print("FN =", FN)
print("TN =", TN)



TP = 19
FP = 0
FN = 0
TN = 26


In [10]:
accuracy = (TP + TN) / (TP + TN + FP + FN)
error_rate = 1 - accuracy
precision = TP / (TP + FP)
recall = TP / (TP + FN)

print("\nModel Performance:")
print("Accuracy   =", accuracy)
print("Error Rate =", error_rate)
print("Precision  =", precision)
print("Recall     =", recall)


Model Performance:
Accuracy   = 1.0
Error Rate = 0.0
Precision  = 1.0
Recall     = 1.0


In [11]:
print("\nOverall Accuracy Score:")
print(accuracy_score(y_test, y_pred))


Overall Accuracy Score:
0.9777777777777777
